// ==ClosureCompiler==
// @output_file_name default.js
// @compilation_level SIMPLE_OPTIMIZATIONS
// @code_url https://googledrive.com/host/0B-fF3VTTcS0SfkRiRHhyUWZtRGs3MDM0dl81aF9BZWxERG1iSVB3cGNpWnNXYXdPZklieDQ/Laker.js
// @code_url https://googledrive.com/host/0B-fF3VTTcS0SfkRiRHhyUWZtRGs3MDM0dl81aF9BZWxERG1iSVB3cGNpWnNXYXdPZklieDQ/Connection.js
// @code_url https://googledrive.com/host/0B-fF3VTTcS0SfkRiRHhyUWZtRGs3MDM0dl81aF9BZWxERG1iSVB3cGNpWnNXYXdPZklieDQ/Game.js
// @code_url https://googledrive.com/host/0B-fF3VTTcS0SfkRiRHhyUWZtRGs3MDM0dl81aF9BZWxERG1iSVB3cGNpWnNXYXdPZklieDQ/Schedule.js
// @code_url https://googledrive.com/host/0B-fF3VTTcS0SfkRiRHhyUWZtRGs3MDM0dl81aF9BZWxERG1iSVB3cGNpWnNXYXdPZklieDQ/Team.js
// @code_url https://googledrive.com/host/0B-fF3VTTcS0SfkRiRHhyUWZtRGs3MDM0dl81aF9BZWxERG1iSVB3cGNpWnNXYXdPZklieDQ/Player.js
// @code_url https://googledrive.com/host/0B-fF3VTTcS0SfkRiRHhyUWZtRGs3MDM0dl81aF9BZWxERG1iSVB3cGNpWnNXYXdPZklieDQ/ScheduleTable.js
// ==/ClosureCompiler==
var Laker=Laker||{};
Laker.html={attr:function(b){var a="",c,g;for(g in b)c=b[g].toString(),a+=g.trim()+"='"+c.trim()+"' ";return a.trim()},tag:function(b,a,c){return"<"+(b+" "+Laker.html.attr(c)).trim()+">"+a+"</"+b+">"},td:function(b,a){return Laker.html.tag("td",b,a)},tr:function(b,a){return Laker.html.tag("tr",b,a)},th:function(b,a){return Laker.html.tag("th",b,a)},Table:function(b){function a(a,d){var b=[];b.addTd=function(a,f){f=e(f)?f:d;b.push(Laker.html.th(a,f));return b};b.toString=function(){return Laker.html.tag("tr",b.join(""),
a)};return b}function c(a,d){var b=[];b.addTd=function(a,f){f=e(f)?f:d;b.push(Laker.html.td(a,f));return b};b.toString=function(){return Laker.html.tag("tr",b.join(""),a)};b.number=0;return b}function g(a,b,c){var h={};h.text=a;h.toString=function(){if(0===h.text.length)return h.text;c=e(c)?c:{};c.colspan=d.Header.length;return Laker.html.tr(Laker.html.td(h.text,c),b)};return h}var d={},e=Laker.utility.isValidObject;d.createHeader=function(b,c){d.Header=new a(b,c);return d.Header};d.createTitle=function(a,
b,c){d.Title=new g(a,b,c);return d.Title};d.Rows=new function(){var a=[];a.add=function(b){a.push(b)};a.toString=function(){return a.join("")};return a};d.createRow=function(a,b){var e=new c(a,b);e.number=d.Rows.length+1;return e};d.toString=function(){var a="";d.Title&&(a+=d.Title.toString());d.Header&&(a+=d.Header.toString());a+=d.Rows.toString();return Laker.html.tag("table",a,b)};return d}};
Laker.style={lakerTitle:{border:"none","font-weight":"bold",padding:"5px 5px 10px 5px","font-size":"larger"},lakerTable:{"border-collapse":"collapse","margin-top":"10px",width:"100%"},lakerHeader:{"background-color":"#7D7D7D",color:"#FFFFFF","font-weight":"normal",padding:"5px",border:"solid #A9A9A9 1px",margin:"0","text-align":"left"},lakerData:{"font-size":"90%",padding:"5px",margin:"0",border:"solid #A9A9A9 1px"},highlightRow:{"font-weight":"bold",color:"#7E4E99","font-size":"110%"},evenRow:{"background-color":"#D5D5D5",
color:"#4A4949"}};Laker.utility={get:function(b){var a="";this.hasOwnProperty(b)&&(a=this[b]);return a},isValidObject:function(b){return void 0!==b&&0<Object.keys(b).length},applyGoogleRecord:function(b,a){var c;$.each(a.split(","),function(a,d){c=d.split(":")[0].trim();b[c]=d.split(":")[1].trim()})}};Laker.Connection=function(b,a){return"https://spreadsheets.google.com/feeds/list/teamKey/sNumType/public/basic?alt=json".replace("teamKey",{varsity:"1qNuIpmdnSH0ecn70ubB6RdVZnhft-05uSg5F-U-ufBg",jv:"1Oa-YOdpg7jZJy0LWHE57jNsiyTP9QYjXXv4riAK_xLk",sophomore:"13DrM1fjPJz-mjsUIbc3DIszJhj2bUpYeRWaMK2afnnc",freshman:"1XWmWiI1GAlO1K18K8qZjERrjTT2ZJNQX_IS7hrxLWB4"}[b]).replace("sNumType",{scores:"1",roster:"2"}[a])};Laker.Game=function(b,a){var c={};c.gamedate=b.trim();Laker.utility.applyGoogleRecord(c,a);c.get=Laker.utility.get;var g="",d,e;d=parseInt(c.get("lakerscore"),10);e=parseInt(c.get("opponentscore"),10);isNaN(d)||isNaN(e)||(g=d>e?"W":d<e?"L":"T");c.result=g;return c};Laker.Schedule=function(b){var a=[];a.wins=0;a.losses=0;a.ties=0;$.each(b.feed.entry,function(b,g){a.push(new Laker.Game(g.title.$t,g.content.$t));switch(a[b].result){case "W":a.wins+=1;break;case "L":a.losses+=1;break;default:a.ties+=1}});return a};Laker.Team=function(b){var a=[],c={};$.each(b.feed.entry,function(b,d){c=new Laker.Player(d);a.push(c)});return a};Laker.Player=function(b){var a={};a.firstname=b.title.$t;a.get=Laker.utility.get;Laker.utility.applyGoogleRecord(a,b.content.$t);a.isCaptain=0<a.get("captain").length;a.fullName=a.firstname+" "+a.get("lastname");return a};$(function(){function b(a,b){var c;c=(0===a%2?"even_row":"odd_row")+(b?" highlight":"");return{"class":c}}function a(){var a=Laker.style,b={"text-align":"center"},c=$.extend({},a.lakerHeader,b),b=$.extend({},a.lakerData,b);$(".laker_title").css(a.lakerTitle);$(".laker_table").css(a.lakerTable);$(".laker_head").css(a.lakerHeader);$(".laker_head_ctr").css(c);$(".laker_data").css(a.lakerData);$(".laker_data_ctr").css(b);$(".even_row").css(a.evenRow);$(".highlight").css(a.highlightRow)}var c=function(){var a=
document.URL.toLowerCase(),b;$.each(["freshman","sophomore","junior-varsity","varsity"],function(c,g){b=g;if(0<a.indexOf(b))return!1});return b}(),g={freshman:"Freshman",sophomore:"Sophomore","junior-varsity":"Junior Varsity",varsity:"Varsity"}[c];$.getJSON(Laker.Connection(c,"scores"),function(c){var e=function(a){var b="";0<a.result.length&&(b=a.result+"&nbsp;"+a.get("lakerscore")+"-"+a.get("opponentscore"));return b};c=new Laker.Schedule(c);var f=new Laker.html.Table({"class":"laker_table"}),l=
f.createHeader({},{"class":"laker_head"}),k={};f.createTitle("2015 "+g+" Schedule",{"class":"laker_title"});l.addTd("DATE").addTd("OPPONENT");l.addTd("LOCATION").addTd("RESULT");$.each(c,function(a,c){k=f.createRow(b(a,"W"===c.result),{"class":"laker_data"});k.addTd(c.gamedate).addTd(c.get("opponent"));k.addTd(c.get("gamelocation")).addTd(e(c));f.Rows.add(k)});$("#scores").append(f.toString());a()});$.getJSON(Laker.Connection(c,"roster"),function(c){c=new Laker.Team(c);var e=new Laker.html.Table({"class":"laker_table"}),
f=e.createHeader({},{"class":"laker_head"}),l={"class":"laker_head_ctr"},k={"class":"laker_data_ctr"},h={};e.createTitle(g+" Roster",{"class":"laker_title"});f.addTd("NAME").addTd("JERSEY",l);f.addTd("GRADE",l).addTd("POSITION",l);$.each(c,function(a,c){h=e.createRow(b(a,c.isCaptain),{"class":"laker_data"});h.addTd(c.fullName).addTd(c.get("number"),k);h.addTd(c.get("grade"),k);h.addTd(c.get("position"),k);e.Rows.add(h)});$("#roster").append(e.toString());a()})});